print('Калькулятор')
a = int(input('Првое число: '))
b = int(input('Второе число: '))
print(f'{a} + {b} = {a + b}')
print(f'{a} - {b} = {a - b}')
print(f'{a} * {b} = {a * b}')
print(f'{a} : {b} = {a / b}')
